#! /bin/bash
# SYNOPSIS npjohn -np <X> (TODO: -hosts <host1,host2,..>) -i     <input_file> [-o <output_file>] ...
echo $1;
if [ $# -eq 1 ] && [ $1 == "-h" ]; 
    then
        cat ./docs/HELP;
    else
        mpirun $1 $2 ./build/main.o ${@:3}
fi